### ISSUE TITLE
Sorting the list of card types in the target settings window.

### ISSUE THREAD

**Issue by Zaxvatov** [Rct567/FrequencyMan#11]
I think it would be good if the sorting matched the one in the ANKI browser. 
I believe it's sorted in ascending order.

![image](https://github.com/user-attachments/assets/dd42ed24-dd26-4fb9-a999-902757b787f7)

**Comment by Rct567** [comment]
Thank you for the suggestion. FrequencyMan currently orders the 'note type' list based on how many cards each 'note type' has. This way, the most likely candidates are at the top. I do understand the suggestion, but I think for the fast majority of users, this is more useful than ordered by name.
