### ISSUE TITLE
Automatic tokenizer don't seem to work for Japanese and Chinese

### ISSUE THREAD

**Issue by herrsilen** [Rct567/FrequencyMan#13]
I have Mecab and Jieba installed as addons for Anki, but FrequencyMan doesn't seem to use them. My sentences are not tokenized, just split where there are commas.

![CleanShot 2024-11-21 at 18 36 53@2x](https://github.com/user-attachments/assets/6e629de1-8781-4fc3-b3c2-19fe92444c54)

Do I need to activate them somehow?

**Comment by Rct567** [comment]
There is no need to activate them.

If you have installed ankimorphs-chinese-jieba and use 'zh' as language id for the specific field, it should work.

Does it say which tokenizer has been used when you reorder your cards?

**Comment by herrsilen** [comment]
First I get this error:

![CleanShot 2024-11-21 at 19 59 40@2x](https://github.com/user-attachments/assets/0efaae07-187a-434b-9eb5-f716d9bb90e7)

Then if I try again, this is the success message:

![CleanShot 2024-11-21 at 20 00 56@2x](https://github.com/user-attachments/assets/114db935-01de-4041-8eb8-b8da1673901f)

This is my setup:

```
[
    {
        "deck": "Japanese",
        "notes": [
            {
                "name": "5. Text comprehension",
                "fields": {
                    "Sentence": "ja"
                }
            }
        ]
    },
    {
        "deck": "Japanese",
        "notes": [
            {
                "name": "2. Audio comprehension",
                "fields": {
                    "Sentence": "ja"
                }
            }
        ]
    },
    {
        "deck": "Japanese",
        "notes": [
            {
                "name": "Kana",
                "fields": {
                    "hiragana": "ja"
                }
            }
        ]
    },
    {
        "deck": "Chinese",
        "notes": [
            {
                "name": "5. Text comprehension",
                "fields": {
                    "Sentence": "zh"
                }
            }
        ]
    },
    {
        "deck": "Chinese",
        "notes": [
            {
                "name": "2. Audio comprehension",
                "fields": {
                    "Sentence": "zh"
                }
            }
        ]
    },
    {
        "deck": "Chinese",
        "notes": [
            {
                "name": "Hanzi",
                "fields": {
                    "Hanzi": "zh"
                }
            }
        ]
    }
]
```

**Comment by herrsilen** [comment]
Anki just warned me about the add-on with this message:

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.0.1-arm64-arm-64bit

Exception ignored in: <function SqlDbFile.__del__ at 0x1167761f0>
Traceback (most recent call last):
  File "/Users/adamsilen/Library/Application Support/Anki2/addons21/909420026/frequencyman/lib/sql_db_file.py", line 194, in __del__
    self.close()
  File "/Users/adamsilen/Library/Application Support/Anki2/addons21/909420026/frequencyman/lib/sql_db_file.py", line 190, in close
    self.__connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12918534144 and this is thread id 8204464704.
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-11-07T02:34, 'None', mod]
Copy notes Fixed by Shige ['800604861', 2024-04-04T05:06, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-11-15T04:46, 'None', mod]
FrequencyMan -  Sort your new cards i1 ['909420026', 2024-09-20T03:33, 'None', mod]
Hanzi Stats ['181243826', 2023-12-03T23:34, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-10-04T04:54, 'None', mod]
ImageResizer ['1214357311', 2023-12-03T02:58, 'None', '']
JapaneseFurigana ['678316993', 2024-08-05T17:46, 'None', mod]
More Overview Stats 21 ['738807903', 2024-08-22T11:14, 'None', '']
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2024-06-04T03:56, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
ankimorphs-chinese-jieba ['1857311956', 2024-03-25T15:52, 'None', '']
ankimorphs-japanese-mecab ['1974309724', 2024-03-21T12:40, 'None', '']

===IDs of active AnkiWeb add-ons===
111623432 1214357311 1771074083 181243826 1857311956 1974309724 2055492159 678316993 738807903 759844606 800604861 876946123 909420026

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiMorphs ['472573498', 2024-10-11T20:37, 'None', mod]

**Comment by Rct567** [comment]
Oh I see you are using macOS. Unfortunately, I have never tested FrequencyMan on macOS. I will try to replicate this issue on Linux. 

Do you get any errors when just reordering the first target (with a fresh Anki start)? What if you delete user_files/cacher_data.sqlite (assuming it exists)?

**Comment by Rct567** [comment]
I think I have been able to replicate the issue. I'll try to fix it as soon as possible.

**Comment by Rct567** [comment]
I have released a new version that should fix this issue. Please note that you might need to delete the file `user_files/cacher_data.sqlite`, as the wrongfully tokenized results might be cached.

**Comment by herrsilen** [comment]
Now it works like a charm! Thanks for fixing it so quickly!

Another issue I ran into now is that it doesn't handle furigana in brackets very well, e.g. 誰[だれ]が 行[い]く？It treats the furigana as separate words and tries to tokenize them as well. Maybe it's easiest to just remove them and put the sentence with furigana into a separate field?
