### ISSUE TITLE
Possible error in Display the amount of mature words

### ISSUE THREAD

**Issue by Zaxvatov** [Rct567/FrequencyMan#14]
Since the overview does not show an example of what this report will look like in statistics, that's why I'm opening this ticket.

At the moment, my report is no different from the standard one. As far as I understand, it is about this tile that we are talking about in the overview.
![image](https://github.com/user-attachments/assets/aa1b5e91-eb73-40a8-b6bc-ef755bf154ed)

I am not an expert in json, so maybe I have the wrong settings. Therefore, I would like to see an example of the entire configuration structure in the overview, if possible.
They look like this now.
![image](https://github.com/user-attachments/assets/8bae356c-5f08-4129-8196-a17b09a46dab)

Full code
`{
    "log_reorder_events": true,
    "reorder_target_list": [
        {
            "deck": "1. Deutsch",
            "notes": [
                {
                    "fields": {
                        "Partizip II": "DE",
                        "Perfekt DE вопрос": "DE",
                        "Perfekt DE утверждение (совершенное. Что сделал?)": "DE",
                        "Perfekt RU вопрос": "RU",
                        "Perfekt RU утверждение": "RU",
                        "Präsens DE вопрос": "DE",
                        "Präsens DE утверждение_1": "DE",
                        "Präsens DE утверждение_2": "DE",
                        "Präsens DE утверждение_3": "DE",
                        "Präsens DE утверждение_4": "DE",
                        "Präsens DE утверждение_5": "DE",
                        "Präsens DE утверждение_6": "DE",
                        "Präsens RU вопрос": "RU",
                        "Präsens RU утверждение_1": "RU",
                        "Präsens RU утверждение_2": "RU",
                        "Präsens RU утверждение_3": "RU",
                        "Präsens RU утверждение_4": "RU",
                        "Präsens RU утверждение_5": "RU",
                        "Präsens RU утверждение_6": "RU",
                        "Präteritum DE вопрос": "DE",
                        "Präteritum DE утверждение (несовершенное. Что делал?)": "DE",
                        "Präteritum RU вопрос": "RU",
                        "Präteritum RU утверждение": "RU",
                        "RU_1": "RU",
                        "RU_2": "RU",
                        "RU_3": "RU",
                        "RU_4": "RU",
                        "RU_5": "RU",
                        "RU_6": "RU",
                        "Инфинитив, Frequency word": "DE",
                        "Спряжение du": "DE",
                        "Спряжение er/sie/es": "DE",
                        "Спряжение ich": "DE",
                        "Спряжение ihr": "DE",
                        "Спряжение sie/Sie": "DE",
                        "Спряжение wir": "DE"
                    },
                    "name": "01. Глагол - общая"
                },
                {
                    "fields": {
                        "DE_1": "DE",
                        "Perfekt DE вопрос": "DE",
                        "Perfekt DE утверждение (совершенное. Что сделал?)": "DE",
                        "Perfekt RU вопрос": "RU",
                        "Perfekt RU утверждение": "RU",
                        "Präsens DE вопрос": "DE",
                        "Präsens DE утверждение_1": "DE",
                        "Präsens DE утверждение_2": "DE",
                        "Präsens DE утверждение_3": "DE",
                        "Präsens RU вопрос": "RU",
                        "Präsens RU утверждение_1": "RU",
                        "Präsens RU утверждение_2": "RU",
                        "Präsens RU утверждение_3": "RU",
                        "Präteritum DE вопрос": "DE",
                        "Präteritum DE утверждение (несовершенное. Что делал?)": "DE",
                        "Präteritum RU вопрос": "RU",
                        "Präteritum RU утверждение": "RU",
                        "RU_1": "RU",
                        "RU_2": "RU",
                        "RU_3": "RU"
                    },
                    "name": "02. Глагол - карточка"
                },
                {
                    "fields": {
                        "DE Ед. ч.": "DE",
                        "DE Мн. ч.": "DE",
                        "RU_1 Ед. ч.": "RU",
                        "RU_1 Мн. ч.": "RU",
                        "RU_2 Ед. ч.": "RU",
                        "RU_2 Мн. ч.": "RU",
                        "RU_3 Ед. ч.": "RU",
                        "RU_3 Мн. ч.": "RU",
                        "RU_4 Ед. ч.": "RU",
                        "RU_4 Мн. ч.": "RU",
                        "RU_5 Ед. ч.": "RU",
                        "RU_5 Мн. ч.": "RU",
                        "RU_6 Ед. ч.": "RU",
                        "RU_6 Мн. ч.": "RU",
                        "context DE_1 Ед. ч.": "DE",
                        "context DE_1 Мн. ч.": "DE",
                        "context DE_2 Ед. ч.": "DE",
                        "context DE_2 Мн. ч.": "DE",
                        "context DE_3 Ед. ч.": "DE",
                        "context DE_3 Мн. ч.": "DE",
                        "context DE_4 Ед. ч.": "DE",
                        "context DE_4 Мн. ч.": "DE",
                        "context DE_5 Ед. ч.": "DE",
                        "context DE_5 Мн. ч.": "DE",
                        "context DE_6 Ед. ч.": "DE",
                        "context DE_6 Мн. ч.": "DE",
                        "context RU_1 Ед. ч.": "RU",
                        "context RU_1 Мн. ч.": "RU",
                        "context RU_2 Ед. ч.": "RU",
                        "context RU_2 Мн. ч.": "RU",
                        "context RU_3 Ед. ч.": "RU",
                        "context RU_3 Мн. ч.": "RU",
                        "context RU_4 Ед. ч.": "RU",
                        "context RU_4 Мн. ч.": "RU",
                        "context RU_5 Ед. ч.": "RU",
                        "context RU_5 Мн. ч.": "RU",
                        "context RU_6 Ед. ч.": "RU",
                        "context RU_6 Мн. ч.": "RU"
                    },
                    "name": "03. Сущ. RU_6 к DE_1"
                },
                {
                    "fields": {
                        "DE Жен. р. Ед. ч.": "DE",
                        "DE Мн. ч.": "DE",
                        "DE Муж. р. Ед. ч.": "DE",
                        "RU Жен. р. Ед. ч.": "RU",
                        "RU Жен. р. Мн. ч.": "RU",
                        "RU Муж. р. Ед. ч.": "RU",
                        "RU Муж. р. Мн. ч.": "RU"
                    },
                    "name": "04. Сущ. гендерное с единой множественной формой"
                },
                {
                    "fields": {
                        "DE_1 Ед. ч.": "DE",
                        "DE_1 Мн. ч.": "DE",
                        "DE_2 Ед. ч.": "DE",
                        "DE_2 Мн. ч.": "DE",
                        "DE_3 Ед. ч.": "DE",
                        "DE_3 Мн. ч.": "DE",
                        "RU Ед. ч.": "RU",
                        "RU Мн. ч.": "RU",
                        "context DE_1 Ед. ч.": "DE",
                        "context DE_1 Мн. ч.": "DE",
                        "context DE_2 Ед. ч.": "DE",
                        "context DE_2 Мн. ч.": "DE",
                        "context RU Ед. ч.": "RU",
                        "context RU Мн. ч.": "RU"
                    },
                    "name": "06. Сущ. RU_1 к DE_3"
                },
                {
                    "fields": {
                        "DE_1": "DE",
                        "DE_2": "DE",
                        "RU_1": "RU",
                        "context DE_1": "DE",
                        "context DE_2": "DE",
                        "context RU_1": "RU",
                        "context RU_2": "RU"
                    },
                    "name": "09. Простая 1:2"
                },
                {
                    "fields": {
                        "DE_1": "DE",
                        "RU_1": "RU",
                        "RU_2": "RU",
                        "RU_3": "RU",
                        "RU_4": "RU",
                        "RU_5": "RU",
                        "RU_6": "RU",
                        "context DE_1": "DE",
                        "context DE_2": "DE",
                        "context DE_3": "DE",
                        "context DE_4": "DE",
                        "context DE_5": "DE",
                        "context DE_6": "DE",
                        "context RU_1": "RU",
                        "context RU_2": "RU",
                        "context RU_3": "RU",
                        "context RU_4": "RU",
                        "context RU_5": "RU",
                        "context RU_6": "RU"
                    },
                    "name": "10. Простая 6:1"
                },
                {
                    "fields": {
                        "DE_1": "DE",
                        "RU_1": "RU"
                    },
                    "name": "11. Числительные"
                },
                {
                    "fields": {
                        "DE общее или дружеское обращение": "DE",
                        "DE официальное обращение": "DE",
                        "RU общее или дружеское обращение": "RU",
                        "RU официальное обращение": "RU"
                    },
                    "name": "12. Фразы"
                },
                {
                    "fields": {
                        "DE_1": "DE",
                        "RU_1": "RU",
                        "context DE_1": "DE",
                        "context RU_1": "RU"
                    },
                    "name": "13. Языковые конструкции"
                }
            ],
            "ranking_factors": {
                "familiarity": 1.0,
                "familiarity_sweetspot": 0.5,
                "ideal_focus_word_count": 4.0,
                "ideal_new_word_count": 0.0,
                "ideal_word_count": 1.0,
                "lexical_underexposure": 0.25,
                "lowest_familiarity": 1.0,
                "lowest_fr_least_familiar_word": 0.25,
                "lowest_word_frequency": 1.0,
                "most_obscure_word": 0.5,
                "new_words": 0.5,
                "no_new_words": 0.0,
                "proper_introduction": 0.1,
                "proper_introduction_dispersed": 0.0,
                "reinforce_learning_words": 1.5,
                "word_frequency": 1.0
            }
        }
    ],
    "show_info_deck_browser": [
        {
            "lang": "DE",
            "target": "*"
        },
        {
            "lang": "RU",
            "target": "*"
        },
        {
            "lang": "DE",
            "target": "id_of_target"
        },
        {
            "lang": "RU",
            "target": "id_of_target"
        }
    ],
    "show_info_toolbar": [
        {
            "lang": "DE",
            "target": "*"
        }
    ]
}`

Version ANKI ⁨24.06.3 (d678e393)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

**Comment by Rct567** [comment]
I think you forgot to set an "id" for the targets you want to display the number of mature words of. This is needed to enable logging, which is required to display the amount of mature words, even if you use "*" inside 'show_info_deck_browser' or 'show_info_toolbar'.

If you define an "id" for a target, you can replace "id_of_target" with that defined "id".

**Comment by Zaxvatov** [comment]
Thanks for the tip!
I don't know if I did everything correctly or not, but I kind of did it. 
![image](https://github.com/user-attachments/assets/e5b08709-e517-4ddf-8e5c-24c9ecae80dd)

I think it would be better if you added a line indicating` "id": "id_of_target",` to the overwiew code.

It is also not entirely clear from the description when to use the "deck" parameter and when to use "decks". 
If possible, it would be good to add a sample code.
At the moment, I have just collected all the target fields for analysis from different subdesks ("name") in "fields". Is this correct?

For "suspended_card_value" and "suspended_leech_card_value", I would also like a more complete description and, possibly, an example code.

The topic can be closed.
