### ISSUE TITLE
Removing the buried state after reorder cards.

### ISSUE THREAD

**Issue by Zaxvatov** [Rct567/FrequencyMan#16]
In the deck settings, I have all three Burying options enabled, which automatically bury sibling and brother cards. These cards are marked with a brown color in the browser.
![image](https://github.com/user-attachments/assets/8cbad056-e9e9-4f4b-a043-4386f030e60c)

But after performing a reorder cards, these states disappear. I don't think this should happen.
![image](https://github.com/user-attachments/assets/9b31a317-1791-42e9-9155-1e3535498cc8)

**Comment by Rct567** [comment]
Are you sure they are not buried anymore? Maybe I missed one, but the cards buried in the first screenshot, don't seem present in the second screenshot.
