### ISSUE TITLE
document corpus_segmentation_strategy

### ISSUE THREAD

**Issue by aleksejrs** [Rct567/FrequencyMan#2]
I guess it is for what I did https://github.com/mortii/anki-morphs/discussions/176 for, but that's not very clear.

**Comment by Rct567** [comment]
I think you just need to define a separate target for what you want to do.

Basically: Separate target == Separate instance of AnkiMorphs

`corpus_segmentation_strategy` is only relevant if you have multiple fields per target.

For example... If you have a target with two fields with the same language:

Front: EN
Back: EN

Should they join, or stay separate, just like how it would be separate if the languages were different from each other?

Front: ES
Back: DE

Using `corpus_segmentation_strategy`: 
- `"by_note_model_id_and_field_name"` will keep them separated in both cases, so there would be two separate corpus data sets (and two sets of all ranking factors for every card in the target).
- `"by_lang_data_id"` would join the first example, as they have the same language, so there would be one corpus data set (and one set of all ranking factors for every card in the target).

**Comment by aleksejrs** [comment]
Thanks! 
https://github.com/Rct567/FrequencyMan#target-settings says "An array of deck names as main scope.", but the list box doesn't allow multiple selection.
