### ISSUE TITLE
<br> is deleted, leaving no space

### ISSUE THREAD

**Issue by aleksejrs** [Rct567/FrequencyMan#6]
Fixed by adding "`br|`" in `        val = re.sub(r'</?(p|div|blockquote|h[1-6]|ul|ol|li|table|tr|td|th)([^>]*)>', ' ', val, flags=re.IGNORECASE)` in `text_processing.py`.

**Comment by Rct567** [comment]
That's expect behavior. <br> is an inline element and should not represent space or be able to divide words. 

As someone else mentioned in the other issue you opened, it's best to correct the notes themselves if you're having issues with this.

**Comment by aleksejrs** [comment]
What the hell?

These pages suggest using it for poems:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br
https://www.w3schools.com/tags/tag_br.asp

Pressing Enter in the note editor adds a `<br>`.
movies2anki turns line breaks in subtitles into `<br>` and/or joins lines with it.

I think the AnkiMorphs dev just wants to avoid adding even a bit of code: https://github.com/mortii/anki-morphs/issues/142

**Comment by Rct567** [comment]
Fair enough. I'll look into it.
